version: '3'

services:

  php-8.2:
    volumes:
      - php82:/workdir
      - "./bin:/workdir/bin:ro"
      - "./src:/workdir/src:ro"
      - "./tests:/workdir/tests:ro"
      - "./composer.json:/workdir/composer.json:ro"
    build:
      context: .
      args:
        IMAGE: php:8.2-cli-alpine
        PACKAGES: git zip unzip icu-dev
    command: '/run-tests.sh'

  php-8.2_intl:
    volumes:
      - php82_intl:/workdir
      - "./bin:/workdir/bin:ro"
      - "./src:/workdir/src:ro"
      - "./tests:/workdir/tests:ro"
      - "./composer.json:/workdir/composer.json:ro"
    build:
      context: .
      args:
        IMAGE: php:8.2-cli-alpine
        PACKAGES: git zip unzip icu-dev
        PHPMODS: intl
    command: '/run-tests.sh'

  php-8.3:
    volumes:
      - php83:/workdir
      - "./bin:/workdir/bin:ro"
      - "./src:/workdir/src:ro"
      - "./tests:/workdir/tests:ro"
      - "./composer.json:/workdir/composer.json:ro"
    build:
      context: .
      args:
        IMAGE: php:8.3-cli-alpine
        PACKAGES: git zip unzip icu-dev
    command: '/run-tests.sh'

  php-8.3_intl:
    volumes:
      - php83_intl:/workdir
      - "./bin:/workdir/bin:ro"
      - "./src:/workdir/src:ro"
      - "./tests:/workdir/tests:ro"
      - "./composer.json:/workdir/composer.json:ro"
    build:
      context: .
      args:
        IMAGE: php:8.3-cli-alpine
        PACKAGES: git zip unzip icu-dev
        PHPMODS: intl
    command: '/run-tests.sh'

  php-8.4:
    volumes:
      - php84:/workdir
      - "./bin:/workdir/bin:ro"
      - "./src:/workdir/src:ro"
      - "./tests:/workdir/tests:ro"
      - "./composer.json:/workdir/composer.json:ro"
    build:
      context: .
      args:
        IMAGE: php:8.4-cli-alpine
        PACKAGES: git zip unzip icu-dev
    command: '/run-tests.sh'

  php-8.4_intl:
    volumes:
      - php84_intl:/workdir
      - "./bin:/workdir/bin:ro"
      - "./src:/workdir/src:ro"
      - "./tests:/workdir/tests:ro"
      - "./composer.json:/workdir/composer.json:ro"
    build:
      context: .
      args:
        IMAGE: php:8.4-cli-alpine
        PACKAGES: git zip unzip icu-dev
        PHPMODS: intl
    command: '/run-tests.sh'

  php-8.5:
    volumes:
      - php85:/workdir
      - "./bin:/workdir/bin:ro"
      - "./src:/workdir/src:ro"
      - "./tests:/workdir/tests:ro"
      - "./composer.json:/workdir/composer.json:ro"
    build:
      context: .
      args:
        IMAGE: php:8.5-cli-alpine
        PACKAGES: git zip unzip icu-dev
    command: '/run-tests.sh'

  php-8.5_intl:
    volumes:
      - php85_intl:/workdir
      - "./bin:/workdir/bin:ro"
      - "./src:/workdir/src:ro"
      - "./tests:/workdir/tests:ro"
      - "./composer.json:/workdir/composer.json:ro"
    build:
      context: .
      args:
        IMAGE: php:8.5-cli-alpine
        PACKAGES: git zip unzip icu-dev
        PHPMODS: intl
    command: '/run-tests.sh'

volumes:
  php82:
  php82_intl:
  php83:
  php83_intl:
  php84:
  php84_intl:
  php85:
  php85_intl:
