on: [push, pull_request]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:

  php-intl:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.2', '8.3', '8.4', '8.5']

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: curl, mbstring, json, intl

      - run: php -v
      - run: php -m
      - run: composer -V
      - run: composer install
      - run: vendor/bin/phpunit --bootstrap tests/bootstrap.php tests
